<?php
$block->executeForm();
$user = $block->getLoggedInUserData();
$block->bulkOrderProcess();
?>

<div id="popup_bo" style="display: none;">
    <div id="popup_box" class="popup-box">
        <div id="close" onclick ="popup_bo_hide()">
            <img src="https://img1.urjacart.in/image/upload/icon/page/close.png" alt="Cross Image" />
        </div>
        <div class="main-content">
            <div class="container">
                <div class="row form-head">
                    <h4><i class="fa fa-cubes" aria-hidden="true"></i> Get unbeatable price for bulk quantity</h4>
                </div>
                <div class="col-md-12 form-content">
                    <form action="<?php echo $block->getProductUrl(); ?>" id="bulkorder" method="post" autocomplete="off">
                        <input type="hidden" name="csrf_token_post" value="<?php echo $block->getBulkCSRFToken(); ?>" >
                        <input type="hidden" name="sku" value="<?php echo $block->getSKU();?>" >
                        <fieldset>
                            <div class="form-group has-float-label">
                                <div class="field">
                                    <input readonly type="text" name="pname" class="form-control required-entry disabled" style="background-color: #f9f9f9;border: 1px solid #CCCCCC;box-shadow: none;" id="p_name"  value="<?php echo $block->getProductName();?>" placeholder="Product name">
                                    <label class="label" for="p_name">Product name</label>
                                </div>
                            </div>
                            <div class="form-group has-float-label">
                                <div class="field left-half">
                                    <div class="input-group">
                                        <input type="button" value='-' class="qtyminuscls qtyclsB" field="quantity" id="qtyminus" onclick="upateQuantity('quantity', 2, 1);" />
                                        <input type="tel"  maxlength="4" tabindex="1" onpaste="return false;" id='quantity' autofocus name='qty' value='1' class='form-control required-entry qty_box'
                                               onkeypress="validateNumInput(event.charCode); return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 0 || event.ctrlKey;" onkeyup="updateQtyByKey(this)" />
                                        <input type="button" id="qtyplus" value='+' class="qtyplus qtyclsB" field="quantity" onclick="upateQuantity('quantity', 1, 1);" />
                                    </div>
                                    <label for="quantity" class="control-label" style="color:#ff5501">Quantity (<i class="fa fa-cubes" aria-hidden="true"></i>)</label>
                                </div>
                                <div class="field right-half">
                                    <input type="number" tabindex="2" id="price" name="price" class="form-control validate-digits "  value="" placeholder="Price"  maxlength="7"
                                           onkeypress="validateNumInput(event.charCode); return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 0 || event.ctrlKey;" />
                                    <label class="label" for="price">Expected price (<i class="fa fa-inr" aria-hidden="true"></i>)</label>
                                </div>
                            </div>
                            <div class="form-group has-float-label">
                                <div class="field">
                                    <input type="text" tabindex="3" class="form-control validate-full-name" id="name" name="name"  minlength="3" maxlength="40" value="<?php echo $user['name']; ?>" placeholder="Name" onkeypress="correctName(this)"/>
                                    <label class="label" for="name"><i class="fa fa-user" aria-hidden="true"></i> Full name</label>
                                </div>
                            </div>
                            <div class="form-group has-float-label">
                                <div class="field">
                                    <input type="tel" tabindex="4" name="mobile"  minlength="10" maxlength="10" class="form-control validate-mobile"  value="<?php echo $user['mobile']; ?>"  placeholder="Mobile"
                                           onkeypress="validateNumInput(event.charCode); return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 0 || event.ctrlKey;" />
                                    <label class="label" for="mobile"><i class="fa fa-mobile" aria-hidden="true"></i> Mobile</label>
                                </div>
                            </div>
                            <div class="form-group has-float-label">
                                <div class="field">
                                    <input type="email" tabindex="5" name="email" maxlength="40" class="form-control validate-email" value="<?php echo $user['email']; ?>" placeholder="Email" onkeypress="return event.charCode != 32" />
                                    <label class="label" for="email"><i class="fa fa-envelope" aria-hidden="true"></i> Email</label>
                                </div>
                            </div>
                            <div class="form-group has-float-label">
                                <div class="field">
                                    <textarea id="remark" tabindex="6" name="remark" class="form-control" rows="2" placeholder="Remark (optional)"   maxlength="250" ></textarea>
                                    <label class="label" for="remark">Remark (if any) - <i class="fa fa-commenting" aria-hidden="true"></i></label>
                                </div>
                            </div>
                            <div class="form-group has-float-label">
                                <div class="field left-half">
                                    <div class="input-group">
                                        <div class="form-control" id="reason" >
                                            <label for="enduse" class="reason">
                                                <input type="radio" tabindex="7" id="enduse" name="user_type" class="enduse required-entry" value="End use" />
                                                <span><i class="fa fa-user" aria-hidden="true"></i> End use</span>
                                            </label>
                                            <label for="resell" class="reason">
                                                <input type="radio" tabindex="7" id="resell" name="user_type"  class="resell required-entry" value="Resell" />
                                                <span><i class="fa fa-exchange" aria-hidden="true"></i> Resell</span>
                                            </label>
                                        </div>
                                    </div>
                                    <label for="user_type" class="control-label">Reason for buying</label>
                                </div>
                            </div>
                        </fieldset>
                        <div class="actions-toolbar">
                            <div class="primary btn-form">
                                <button type="submit" id="button_bo" tabindex="8" name="bulksubmit" class="btn button_submit" onclick="error_check()" value="bulksubmit"><i class="fa fa-cubes" aria-hidden="true"></i> Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/x-magento-init">
    {
        "#bulkorder": {
            "validation": {}
        }
    }
</script>

<script type="text/javascript">

    //Function To Display Popup
    function popup_bo_show() {
        document.getElementById('popup_bo').style.display = "block";
        document.getElementById("quantity").focus();
    }
    //Function to Hide Popup
    function popup_bo_hide(){
        document.getElementById('popup_bo').style.display = "none";
    }

    function validateNumInput(charCode) {
        if (!(typeof charCode === 'boolean' || (charCode >= 48 && charCode <= 57))) {
            return false;
        }
    }
    function error_check(){
        if (document.getElementById('enduse').checked) {
            document.getElementById('reason').style.border = '1px solid #ccc';
        }else if (document.getElementById('resell').checked) {
            document.getElementById('reason').style.border = '1px solid #ccc';
        }else {
            document.getElementById('reason').style.border = '1px solid #FF0000';
        }
    }

    require(['jquery'],function(jQuery) {
        jQuery(document).keyup(function(e) {
          var code = e.keyCode || e.which;
          if(code == 27) { //Enter keycode
           document.getElementById('popup_bo').style.display = "none";
          }
        });
//        jQuery(document).ready(function () {
//            // This button will increment the value
//            jQuery('.qtyplus').click(function (e) {
//                e.preventDefault();
//                var currentVal = parseInt(jQuery('#qtyf').val());
//                if (!isNaN(currentVal)) {
//                    jQuery('#qtyf').val(currentVal + 1);
//                } else {
//                    jQuery('#qtyf').val(1);
//                }
//            });
//            // This button will decrement the value till 1
//            jQuery(".qtyminus").click(function (e) {
//                e.preventDefault();
//                var currentVal = parseInt(jQuery('#qtyf').val());
//                if (!isNaN(currentVal) && currentVal > 1) {
//                    jQuery('#qtyf').val(currentVal - 1);
//                } else {
//                    jQuery('#qtyf').val(1);
//                }
//            });
//        });
    });

</script>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$fProduct = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$brandName = $fProduct->getResource()->getAttribute("manufacturer")->getFrontend()->getValue($fProduct);
$modelName = $fProduct->getResource()->getAttribute("model_no")->getFrontend()->getValue($fProduct);
$categoryIdList = $fProduct->getCategoryIds();
$i = 1;
$categoryIds = array();
foreach($categoryIdList as $catid){
    $data = $objectManager->create('Magento\Catalog\Model\Category')->load($catid);
    $categoryIds[$data->getLevel()] = $catid;
}
ksort($categoryIds);
foreach($categoryIds as $category){
    $cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
    ${catnamel.$i} = $cat->getName();
    $i++;
}
unset($_SESSION['refB']);
$fullName = $this->getRequest()->getPost('name');
$nameData = explode(' ',trim($fullName));
$fName = $nameData[0];
$lName = $nameData[1];
?>
<script>
    var refno = '<?php echo $block->refNo(); ?>';
    if(refno){
        mixpanel.register({
                "First Name":"<?php echo $fName;?>",
                "Last Name":"<?php echo $lName;?>",
                "Email":"<?php echo $this->getRequest()->getPost('email');?>",
                "Mobile":"<?php echo $this->getRequest()->getPost('mobile');?>"
        });
        mixpanel.track(
            "Submitted Product Bulk Order",
            {
                "Product Name": '<?php echo $fProduct->getName();?>',
                "Product Category L1": "<?php echo $catnamel1; ?>",
                "Product Category L2": "<?php echo $catnamel2; ?>",
                "Product Category L3": "<?php echo $catnamel3; ?>",
                "Product Price":<?php if($fProduct->getSpecialPrice()): ?><?php echo substr($fProduct->getSpecialPrice(),0,-5); ?><?php else: ?><?php echo substr($fProduct->getPrice(),0,-5); ?><?php endif; ?>,
                "Product Brand":"<?php echo $brandName;?>",
                "Product Quantity":"<?php echo $this->getRequest()->getPost('qty');?>",
                "Buying Purpose":"<?php echo $this->getRequest()->getPost('user_type');?>"
            }
        );
        mixpanel.people.set({
            "$first_name": "<?php echo $fName;?>",
            "$last_name": "<?php echo $lName;?>",
            "$email": "<?php echo $this->getRequest()->getPost('email');?>",
            "$phone":"<?php echo $this->getRequest()->getPost('mobile');?>"
        });

        fbq('track', 'Lead', {
            value: <?php echo $fProduct->getSpecialPrice() ? round($fProduct->getSpecialPrice()) : round($fProduct->getPrice()); ?>,
            currency:'INR',
            content_ids:'<?php echo $fProduct->getSku();?>',
            content_name:'<?php echo $fProduct->getName();?>',
            content_category: '<?php echo $catnamel3; ?>',
            num_items: document.getElementById('qty').value,
            content_type: 'product'
        });
    }

    function upateQuantity(id, updateType, delta) {
        var currentVal = parseInt(document.getElementById(id).value);
        if (!isNaN(currentVal) && currentVal === 9999 && updateType == 1) {
            document.getElementById(id).value = currentVal;
            document.getElementById('qtyplus').disabled = true;
        } else if (!isNaN(currentVal) && updateType == 1) {
            document.getElementById(id).value = currentVal + delta;
            document.getElementById('qtyminus').disabled = false;
        } else if (!isNaN(currentVal) && updateType == 2) {
            document.getElementById('qtyplus').disabled = false;
            var diff  = currentVal - delta;
            if(diff > 0) {
                document.getElementById(id).value = currentVal - delta;
            } else {
                document.getElementById('qtyminus').disabled = true;
            }
        } else {
            document.getElementById(id).value = 1;
        }
    }

    function updateQtyByKey(self) {
        if (parseInt(self.value) === 0) {
            self.value = 1;
            document.getElementById('qtyminus').disabled = true;
            document.getElementById('qtyplus').disabled = false;
        } else if (self.value == 9999) {
            document.getElementById('qtyplus').disabled = true;
            document.getElementById('qtyminus').disabled = false;
        } else {
            document.getElementById('qtyminus').disabled = false;
            document.getElementById('qtyplus').disabled = false;
        }
    }

    function correctName(self) {
        var data = self.value;
        if (!(/^[a-zA-Z]+ ?([a-zA-Z]*) ?([a-zA-Z]*)$/i.test(data))) {
            self.value = data.trim();
        }
    }
</script>
