<?php
$block->executeForm();
$user = $block->getLoggedInUserData();
$block->bulkOrderProcess();
?>

<div class="main-content mobilebulkorderformbox">
<a href="<?php echo $_SESSION['backUrl']; ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Back</a>
    <div class="container">
        <div class="row form-head mobileFrmHead">
            <h4><i class="fa fa-cubes" aria-hidden="true"></i><br /> Get unbeatable price <br/> for bulk quantity</h4>
        </div>
        <div class="row form-content">
            <form action="<?php echo $block->getProductUrl(); ?>" id="bulkorder" onsubmit="bulkOrderTracking()" method="post" autocomplete="off">
                <input type="hidden" name="csrf_token_post" value="<?php echo $block->getBulkCSRFToken(); ?>" >
                <input type="hidden" name="murl" value="mbulkorder" >
                <fieldset>
                    <div class="form-group has-float-label">
                        <div class="field">
                            <input readonly type="text" name="pname" class="form-control required-entry disabled" style="background-color: #f9f9f9;border: 1px solid #CCCCCC;box-shadow: none;" id="p_name"  value="<?php echo $_SESSION['productName'];?>" placeholder="Product name">
                            <label class="label" for="p_name">Product name</label>
                        </div>
                    </div>
                    <div class="form-group has-float-label">
                        <div class="field left-half">
                            <div class="input-group">
                                <input type="button" value='-' class="qtyminuscls qtyclsB" field="quantity" id="qtyminus" onclick="upateQuantity('quantity', 2, 1);" />
                                <input type="tel" autofocus id='quantity' onpaste="return false;" name='qty' minlength="1" maxlength="4" value='1' class='form-control qty_box required-entry'  onkeypress='validateNumInput(event.charCode);  return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 0 || event.ctrlKey;' onkeyup="updateQtyByKey(this)"/>
                                <input type="button" tabindex="1" id="qtyplus" value='+' class="qtyplus qtyclsB" field="quantity" onclick="upateQuantity('quantity', 1, 1);" />
                            </div>
                            <label for="quantity" class="control-label" style="color:#ff5501">Qty. (<i class="fa fa-cubes" aria-hidden="true"></i>)</label>
                        </div>
                        <div class="field right-half">
                            <input type="number" tabindex="2" id="price" name="price" class="form-control exp-price "   value="" placeholder="Price"  maxlength="9"
                                   onkeypress="validateNumInput(event.charCode); return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 0 || event.ctrlKey;" />
                            <label class="label" for="price">Expected price (<i class="fa fa-inr" aria-hidden="true"></i>)</label>
                        </div>
                    </div>
                    <div class="form-group has-float-label">
                        <div class="field">
                            <input type="text" tabindex="3" class="form-control validate-full-name" id="name" name="name" minlength="3" maxlength="40" value="<?php echo $user['name']; ?>" placeholder="Name" onkeypress="correctName(this)" />
                            <label class="label" for="name"><i class="fa fa-user" aria-hidden="true"></i> Full name</label>
                        </div>
                    </div>
                    <div class="form-group has-float-label">
                        <div class="field">
                            <input type="tel" tabindex="4" name="mobile" id="bmobile" minlength="10" maxlength="10" class="form-control validate-mobile"  value="<?php echo $user['mobile']; ?>" placeholder="Mobile"
                                   onkeypress="validateNumInput(event.charCode); return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 0 || event.ctrlKey;" />
                            <label class="label" for="mobile"><i class="fa fa-mobile" aria-hidden="true"></i> Mobile</label>
                        </div>
                    </div>
                    <div class="form-group has-float-label">
                        <div class="field">
                            <input type="email" tabindex="5" name="email" id="bemail" maxlength="40" class="form-control validate-email"  value="<?php echo $user['email']; ?>" placeholder="Email" onkeypress="return event.charCode != 32"/>
                            <label class="label" for="email"><i class="fa fa-envelope" aria-hidden="true"></i> Email</label>
                        </div>
                    </div>
                    <div class="form-group has-float-label">
                        <div class="field">
                            <textarea id="remark" tabindex="6" name="remark" class="form-control" rows="2" placeholder="Remark (optional)"   maxlength="250" ></textarea>
                            <label class="label" for="remark">Remark (if any) - <i class="fa fa-commenting" aria-hidden="true"></i></label>
                        </div>
                    </div>
                    <div class="form-group has-float-label">
                        <div class="field">
                            <div class="input-group">
                                <div class="form-control" id="reason" >
                                    <label for="enduse" class="reason">
                                        <input type="radio" tabindex="7" id="enduse" name="user_type" class="enduse required-entry" value="End use" />
                                        <span><i class="fa fa-user" aria-hidden="true"></i> End use</span>
                                    </label>
                                    <label for="resell" class="reason">
                                        <input type="radio" tabindex="8" id="resell" name="user_type"  class="resell required-entry" value="Resell" />
                                        <span><i class="fa fa-exchange" aria-hidden="true"></i> Resell</span>
                                    </label>
                                </div>
                            </div>
                            <label for="user_type" class="control-label">Reason for buying</label>
                        </div>
                    </div>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary btn-form">
                        <button type="submit" id="button_bo" tabindex="9" name="bulksubmit" class="btn button_submit" onclick="error_check()" value="bulksubmit"><i class="fa fa-cubes" aria-hidden="true"></i> Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#bulkorder": {
            "validation": {}
        }
    }
</script>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productFactory = $objectManager->get('Magento\Catalog\Model\Product');
$categoryFactory = $objectManager->get('Magento\Catalog\Model\Category');
$_product = $productFactory->loadByAttribute('sku', $_SESSION['fsku']);
//var_dump($_SESSION['fsku']); die;
//var_dump($_product->getAttributeText('manufacturer')); die;
$categoryIdList = $_product->getCategoryIds();
$i = 1;
$categoryIds = array();
foreach($categoryIdList as $catid){
    $data = $categoryFactory->load($catid);
    $categoryIds[$data->getLevel()] = $catid;
}
ksort($categoryIds);
foreach($categoryIds as $category){
    $cat = $categoryFactory->load($category);
    ${categoryL.$i} = $cat->getName();
    $i++;
}
?>
<script type="text/javascript">

    function error_check(){
        if (document.getElementById('enduse').checked) {
            document.getElementById('reason').style.border = '1px solid #ccc';
        }else if (document.getElementById('resell').checked) {
            document.getElementById('reason').style.border = '1px solid #ccc';
        }else {
            document.getElementById('reason').style.border = '1px solid #FF0000';
        }
    }
    function validateNumInput(charCode) {
        if (!(typeof charCode === 'boolean' || (charCode >= 48 && charCode <= 57))) {
            return false;
        }
    }

    function bulkOrderTracking() {
        var qty = document.getElementById('quantity').value;
        var name = document.getElementById('name').value;
        var mobile = document.getElementById('bmobile').value;
        var email = document.getElementById('bemail').value;
        var enduse = document.getElementById('enduse').value;
        var resell = document.getElementById('resell').value;
        var nameArr = [];
        if (qty < 1) {
            return false;
        }
        if (name !== '' && /^[a-zA-Z ]+$/.test(name)) {
            name = name.split(' ');
            for (var i=0; i < name.length; i++) {
                if (name[i]) {
                    nameArr.push(name[i]);
                }
            }
        } else {
            return false;
        }
        if (!(mobile !== '' && /^[6-9]{1}[0-9]{9}$/.test(mobile))) {
            return false;
        }
        if (!(email !== '' && /^([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*@([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*\.(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]){2,})$/i.test(email))) {
            return false;
        }
        if (!(enduse == 'End use' || resell != 'Resell')) {
            return false;
        }
        var user_type = enduse ? enduse : resell;
        mixpanel.register({
            "First Name": nameArr[0],
            "Last Name": nameArr[1],
            "Email": email,
            "Mobile": mobile
        });
        mixpanel.track(
            "Submitted Product Bulk Order",
            {
                "Product Name": '<?php echo $_product->getName(); ?>',
                "Product SKU": '<?php echo $_SESSION['fsku']; ?>',
                "Product Category L1": "<?php echo $categoryL1; ?>",
                "Product Category L2": "<?php echo $categoryL2; ?>",
                "Product Category L3": "<?php echo $categoryL3; ?>",
                "Product Price": <?php echo $price = $_product->getSpecialPrice() ? round($_product->getSpecialPrice()) : round($_product->getPrice()); ?>,
                "Product Brand":"<?php echo $_SESSION['brand']; ?>",
                "Product Quantity": qty,
                "Buying Purpose": user_type
            }
        );
        mixpanel.people.set({
            "$first_name": nameArr[0],
            "$last_name": nameArr[1],
            "$email": email,
            "$phone": mobile
        });
    }

    function upateQuantity(id, updateType, delta) {
        var currentVal = parseInt(document.getElementById(id).value);
        if (!isNaN(currentVal) && currentVal === 9999 && updateType == 1) {
            document.getElementById(id).value = currentVal;
            document.getElementById('qtyplus').disabled = true;
        } else if (!isNaN(currentVal) && updateType == 1) {
            document.getElementById(id).value = currentVal + delta;
            document.getElementById('qtyminus').disabled = false;
        } else if (!isNaN(currentVal) && updateType == 2) {
            document.getElementById('qtyplus').disabled = false;
            var diff  = currentVal - delta;
            if(diff > 0) {
                document.getElementById(id).value = currentVal - delta;
            } else {
                document.getElementById('qtyminus').disabled = true;
            }
        } else {
            document.getElementById(id).value = 1;
        }
    }

    function updateQtyByKey(self) {
        if (parseInt(self.value) === 0) {
            self.value = 1;
            document.getElementById('qtyminus').disabled = true;
            document.getElementById('qtyplus').disabled = false;
        } else if (self.value == 9999) {
            document.getElementById('qtyplus').disabled = true;
            document.getElementById('qtyminus').disabled = false;
        } else {
            document.getElementById('qtyminus').disabled = false;
            document.getElementById('qtyplus').disabled = false;
        }
    }

    function correctName(self) {
        var data = self.value;
        if (!(/^[a-zA-Z]+ ?([a-zA-Z]*) ?([a-zA-Z]*)$/i.test(data))) {
            self.value = data.trim();
        }
    }
</script>
