<div class="custom-order-form-content">
    <div class="form-banner">
        <img src="https://img1.urjacart.in/image/upload/icon/page/custom-order-form-banner.jpg" class="" alt="Custom order form" />
    </div>
    <div class="clear"></div>
    <div class="form-head-content">
        <div class="form-content">
            <div class="form-points">
                <div class="col-md-6 points">
                    <div class="row">
                        <span class="credit"></span>
                        <p>Credit option available</p>
                    </div>
                </div>
                <div class="col-md-6 points">
                    <div class="row">
                        <span class="bulk"></span>
                        <p>Best price for bulk orders</p>
                    </div>
                </div>
                <div class="col-md-6 points">
                    <div class="row">
                        <span class="domain"></span>
                        <p>Domain expert consultant</p>
                    </div>
                </div>
                <div class="col-md-6 points">
                    <div class="row">
                        <span class="delivery"></span>
                        <p>Nationwide Delivery</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clear"></div>
</div>

