<div class="header-bg">
    <div class="container container-head">
        <div class="row">
            <header class="clearfix">
                <div class="col-xs-12 col-sm-4 col-md-6 top_logo m-navigation">
                    <a class="cart-logo" href="<?php echo $block->getUrl(''); ?>" title="Urjakart">
                        <div class="logo_img" ></div>
                    </a>
                </div>
                <div class="col-xs-12 col-sm-8 col-md-6 right_contact">
                    <div class="support">
                        <a href="tel:+91-8010-978-978">
                            <i class="fa fa-phone"></i>+91-8010-978-978
                        </a>
                        <a href="mailto:support@urjakart.com">
                            <i class="fa fa-envelope"></i>support@urjakart.com
                        </a>
                    </div>
                </div>
            </header>
        </div>
    </div>
</div>
<section class="section uk-seller-section-background mb-4">
 <div class="container">
    <div class="row justify-content-end">
        <div class="col-lg-6 col-md-6">
            <h2 class="uk-top-head">"With Urjakart, my products reach lakhs of customers effortlessly.
            As simple as that."
            </h2>
            <h4>
                Mukesh Yadav<br>
                #OnlineMarketPlace
            </h4>
        </div>
    </div>

 </div>

</section>
