<?php
$block->executeForm();
$user = $block->getLoggedInUserData();
$block->becomeSeller();
?>

<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sell-on-urjakart-cont')->toHtml(); ?>

<section class="uk-seller-form-section-4">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 justify-content-center text-center">
                <h2>Start your business with Urjakart.</h2>
                <p class="font-big-p">Start your business with Urjakart & reach customers across India</p>
                <div id="uk-seller-fButton" class="uk-seller-formopenBtn">Click Here</div>
            </div>
            <div class="col-lg-12" id="newpost">
                <div class="col-centered-custom">
                    <div class="formheader">
                        Get the Best deal with us for your business.<br>
                        <span>Please fill out the form below and We will contact you shortly.</span>
                    </div>
                    <form action="<?php echo $block->getFormAction(); ?>" class="form-container" id="becomeukseller"
                          method="post"
                          autocomplete="off" enctype="multipart/form-data">
                        <section class="form-content uk-sellerform">
                            <input type="hidden" name="csrf_token_post" value="<?php echo $block->getCSRFToken(); ?>">
                            <fieldset>
                                <div class="form-group has-float-label">
                                    <div class="field">
                                        <input class="form-control validate-name"
                                               minlength="3" maxlength="40" value="<?php echo $user['name']; ?>"
                                               type="text" id="name" name="name" placeholder="Name" tabindex="1" onkeypress="correctName(this)"/>
                                        <label class="label" for="name">Name</label>
                                    </div>
                                </div>

                                <div class="form-group has-float-label">
                                    <div class="field">
                                        <input class="form-control validate-email" maxlength="40"
                                               value="<?php echo $user['email']; ?>" type="email" id="email" name="email" placeholder="Email" tabindex="2" onkeypress="return event.charCode != 32"/>
                                        <label class="label" for="email">Email</label>
                                    </div>
                                </div>

                                <div class="form-group has-float-label">
                                    <div class="field">
                                        <input class="form-control validate-mobile" minlength="10"
                                               maxlength="10" value="<?php echo $user['mobile']; ?>" type="tel" id="mobile" name="mobile"
                                               onkeypress="validateNumInput(event.charCode); return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 0 || event.ctrlKey;" placeholder="Mobile" tabindex="3"/>
                                        <label class="label" for="mobile">Mobile</label>
                                    </div>
                                </div>

                                <div class="form-group has-float-label">
                                    <div class="field">
                                        <input class="form-control validate-company-name"
                                               maxlength="50" type="text" id="company-name" name="company_name" placeholder="Company name" tabindex="4"/>
                                        <label class="label" for="company-name">Company name</label>
                                    </div>
                                </div>

                                <div class="form-group has-float-label">
                                    <div class="field">
                                        <input class="form-control validate-brand-deal"
                                               maxlength="50" type="text" id="oem" name="oem" placeholder="OEM/Distributor For" tabindex="5"/>
                                        <label class="label" for="oem">OEM/Distributor For (Eg - Bajaj, Bosch...)</label>
                                    </div>
                                </div>

                                <div class="input file-uload1 uk-upload-seller">
                                    <h4>Upload Authorization Certificate :</h4>
                                    <label for="Field11" class="uploadButton2"><i class="glyphicon glyphicon-open"></i></label>
                                    <input type="file" name="Field11" id="Field11" class="input-text" onchange="validateFile(this.id)" tabindex="6"/>
                                    <p class="file-name1" id="file_cert_id">You can upload photo or pdf related to your requirement.</p>
                                    <a style="color: red; display: none;cursor:pointer;" tilte="Remove file" id="clearfilecert" onclick="clearFileCert()">Remove</a>
                                    <p class="file-name1 mage-error" id="mage_cert_error" style="color:#e02b27;"></p>
                                </div>
                                <div class="input file-uload2 uk-upload-seller">
                                    <h4>Upload Catalog/Pricelist :</h4>
                                    <label for="Field12" class="uploadButton2"><i class="glyphicon glyphicon-open"></i></label>
                                    <input type="file" name="Field12" id="Field12" class="input-text" onchange="validateFile(this.id)" tabindex="7"/>
                                    <p class="file-name2" id="file_price_id">You can upload photo or pdf related to your requirement.</p>
                                    <a style="color: red; display: none;cursor:pointer;" tilte="Remove file" id="clearfilepl" onclick="clearFilePl()">Remove</a>
                                    <p class="file-name2 mage-error" id="mage_price_error" style="color:#e02b27;"></p>
                                </div>
                                <div class="input container-radio-center uk-sellerForm">
                                    <h4>Do you sell on other websites too? :</h4>
                                    <input type="radio" value="Yes" id="radio1" name="sell" checked="checked" tabindex="8"/>
                                    <label class="sellerLabel-cc radio1 item" for="radio1"></label>
                                    <input type="radio" value="No" id="radio2" name="sell"/>
                                    <label class="sellerLabel-cc radio2 item" for="radio2"></label>
                                </div>

                            </fieldset>
                        </section>
                        <span class="input">
                            <button type="submit" name="VENDOR" class="submit-but-ukform-bulk" id="ukform-seller" tabindex="9">Submit</button>
                        </span>
                    </form><!-- /form -->
                </div>
            </div>
        </div>
    </div>
    <input type="hidden" id="doc_count" value="0" />
</section>

<script type="text/x-magento-init">
    {
        "#becomeukseller": {
            "validation": {}
        }
    }
</script>

<script type="text/javascript">
    require(['jquery'], function (jQuery) {
        jQuery(function (jQuery) {
            jQuery('input[type="file"]').change(function () {
                if (jQuery(this).val()) {
                    var filename = jQuery(this).val();
                    jQuery(this).closest('.file-uload1').find('#file_cert_id').html(filename);
                    jQuery(this).closest('.file-uload2').find('#file_price_id').html(filename);
                }
            });

            jQuery("#uk-seller-fButton").click(function () {
                jQuery("#newpost").slideToggle("slow");
                jQuery("#uk-seller-fButton").hide();
            });


        });
    });

    function validateNumInput(charCode) {
        if (!(typeof charCode === 'boolean' || (charCode >= 48 && charCode <= 57))) {
            return false;
        }
    }

    function validateFile(id) {
        var file = document.getElementById(id);
        var file_size = file.files.item(0).size;
        var file_name = file.files.item(0).name;
        var error = '';
        var error_display;
        var clearfile;
        if (id == 'Field11') {
            error_display = document.getElementById('mage_cert_error');
            clearfile = document.getElementById('clearfilecert');
        }
        if (id == 'Field12') {
            error_display = document.getElementById('mage_price_error');
            clearfile = document.getElementById('clearfilepl');
        }
        var btn = document.getElementById('ukform-seller');
        var count = document.getElementById('doc_count');
        error_display.innerHTML = error;
        if (file_size > 2500000) {
            error += 'File must less than 2.5MB<br>';
        }
        var extension = ['png', 'jpg', 'jpeg', 'gif', 'doc', 'docx', 'txt', 'odt', 'xls', 'ods', 'pdf'];
        var file_ext = file_name.split('.');
        file_ext = file_ext[1] || '';
        file_ext = file_ext.toLowerCase();
        if (extension.indexOf(file_ext) == -1) {
            error += 'File must be .png, .jpeg, .jpg, .gif, .doc, .docx, .txt, .xls, .ods, .odt, .pdf only';
        }
        if (error != '') {
            error_display.innerHTML = error;
            btn.disabled = true;
            clearfile.style.display = 'inline-block';
            if (count.value < 2)
                count.value = parseInt(count.value) + 1;
        } else {
            error_display.innerHTML = '';
            clearfile.style.display = 'none';
            if (count.value > 0)
                count.value = parseInt(count.value) - 1;
            if (count.value == 0)
                btn.disabled = false;
        }
    }

    function clearFileCert() {
        if (document.getElementById('doc_count').value > 0)
            document.getElementById('doc_count').value = parseInt(document.getElementById('doc_count').value) - 1;
        if (document.getElementById('doc_count').value == 0)
            document.getElementById('ukform-seller').disabled = false;
        document.getElementById('mage_cert_error').innerHTML = '';
        document.getElementById('clearfilecert').style.display = 'none';
        document.getElementById('Field11').value = '';
    }

    function clearFilePl() {
        if (document.getElementById('doc_count').value > 0)
            document.getElementById('doc_count').value = parseInt(document.getElementById('doc_count').value) - 1;
        if (document.getElementById('doc_count').value == 0)
            document.getElementById('ukform-seller').disabled = false;
        document.getElementById('mage_price_error').innerHTML = '';
        document.getElementById('clearfilepl').style.display = 'none';
        document.getElementById('Field12').value = '';
    }

    function correctName(self) {
        var data = self.value;
        if (!(/^[a-zA-Z]+ ?([a-zA-Z]*) ?([a-zA-Z]*)$/i.test(data))) {
            self.value = data.trim();
        }
    }

</script>